# Generated by Django 3.0.2 on 2020-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('dateUploaded', models.DateTimeField(auto_now=True)),
                ('streamType', models.TextField(max_length=10)),
                ('url', models.TextField(max_length=500)),
            ],
        ),
    ]
