# Generated by Django 3.0.2 on 2020-02-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='poster',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
